#oauth2_auth:
#  path: '/oauth/auth'
#  controller: '@TrikoderOAuth2Bundle\Controller\AuthorizationController::indexAction'
#  method: GET
#
#oauth2_token:
#  path: '/oauth/token'
#  controller: '@TrikoderOAuth2Bundle\Controller\TokenController::indexAction'
#  method: POST
